-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.ai_analysis_queue (
  id bigint NOT NULL DEFAULT nextval('ai_analysis_queue_id_seq'::regclass),
  report_id integer NOT NULL,
  visit_id integer NOT NULL,
  patient_id integer NOT NULL,
  doctor_firebase_uid text NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])),
  priority integer DEFAULT 1 CHECK (priority >= 1 AND priority <= 3),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  retry_count integer DEFAULT 0 CHECK (retry_count >= 0),
  max_retries integer DEFAULT 3,
  error_message text,
  queued_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_analysis_queue_pkey PRIMARY KEY (id),
  CONSTRAINT fk_queue_report FOREIGN KEY (report_id) REFERENCES public.reports(id),
  CONSTRAINT fk_queue_visit FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT fk_queue_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT fk_queue_doctor FOREIGN KEY (doctor_firebase_uid) REFERENCES public.doctors(firebase_uid)
);
CREATE TABLE public.ai_consolidated_analysis (
  id bigint NOT NULL DEFAULT nextval('ai_consolidated_analysis_id_seq'::regclass),
  visit_id integer NOT NULL,
  patient_id integer NOT NULL,
  doctor_firebase_uid text NOT NULL,
  report_ids ARRAY NOT NULL,
  document_count integer NOT NULL DEFAULT 1 CHECK (document_count > 0),
  model_used character varying NOT NULL DEFAULT 'gemini-2.0-flash-exp'::character varying,
  confidence_score numeric DEFAULT 0.70 CHECK (confidence_score >= 0.0 AND confidence_score <= 1.0),
  raw_analysis text NOT NULL,
  overall_assessment text,
  clinical_picture text,
  integrated_recommendations text,
  patient_summary text,
  consolidated_findings jsonb,
  priority_actions jsonb,
  analysis_success boolean DEFAULT true,
  analysis_error text,
  processing_time_ms integer,
  analyzed_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_consolidated_analysis_pkey PRIMARY KEY (id),
  CONSTRAINT fk_ai_consolidated_visit FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT fk_ai_consolidated_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT fk_ai_consolidated_doctor FOREIGN KEY (doctor_firebase_uid) REFERENCES public.doctors(firebase_uid)
);
CREATE TABLE public.ai_document_analysis (
  id bigint NOT NULL DEFAULT nextval('ai_document_analysis_id_seq'::regclass),
  report_id integer NOT NULL,
  visit_id integer NOT NULL,
  patient_id integer NOT NULL,
  doctor_firebase_uid text NOT NULL,
  analysis_type character varying NOT NULL DEFAULT 'document_analysis'::character varying,
  model_used character varying NOT NULL DEFAULT 'gemini-2.0-flash-exp'::character varying,
  confidence_score numeric DEFAULT 0.70 CHECK (confidence_score >= 0.0 AND confidence_score <= 1.0),
  raw_analysis text NOT NULL,
  document_summary text,
  clinical_significance text,
  correlation_with_patient text,
  actionable_insights text,
  patient_communication text,
  clinical_notes text,
  key_findings jsonb,
  analysis_success boolean DEFAULT true,
  analysis_error text,
  processing_time_ms integer,
  analyzed_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  clinical_correlation text,
  detailed_findings text,
  critical_findings text,
  treatment_evaluation text,
  CONSTRAINT ai_document_analysis_pkey PRIMARY KEY (id),
  CONSTRAINT fk_ai_analysis_report FOREIGN KEY (report_id) REFERENCES public.reports(id),
  CONSTRAINT fk_ai_analysis_visit FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT fk_ai_analysis_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT fk_ai_analysis_doctor FOREIGN KEY (doctor_firebase_uid) REFERENCES public.doctors(firebase_uid)
);
CREATE TABLE public.appointments (
  id bigint NOT NULL DEFAULT nextval('appointments_id_seq'::regclass),
  doctor_firebase_uid text NOT NULL,
  patient_id bigint,
  frontdesk_user_id integer,
  appointment_date date NOT NULL,
  appointment_time time without time zone NOT NULL,
  duration_minutes integer DEFAULT 30 CHECK (duration_minutes > 0),
  status character varying NOT NULL DEFAULT 'scheduled'::character varying CHECK (status::text = ANY (ARRAY['scheduled'::character varying::text, 'confirmed'::character varying::text, 'in_progress'::character varying::text, 'completed'::character varying::text, 'cancelled'::character varying::text, 'no_show'::character varying::text])),
  appointment_type character varying DEFAULT 'consultation'::character varying,
  notes text,
  patient_notes text,
  created_by_frontdesk boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT appointments_pkey PRIMARY KEY (id),
  CONSTRAINT fk_appointments_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT fk_appointments_doctor FOREIGN KEY (doctor_firebase_uid) REFERENCES public.doctors(firebase_uid),
  CONSTRAINT fk_appointments_frontdesk FOREIGN KEY (frontdesk_user_id) REFERENCES public.frontdesk_users(id)
);
CREATE TABLE public.calendar_notifications (
  id bigint NOT NULL DEFAULT nextval('calendar_notifications_id_seq'::regclass),
  doctor_firebase_uid text NOT NULL,
  notification_type character varying NOT NULL CHECK (notification_type::text = ANY (ARRAY['email'::character varying, 'sms'::character varying, 'whatsapp'::character varying, 'push'::character varying]::text[])),
  days_before integer NOT NULL DEFAULT 1 CHECK (days_before >= 0),
  is_enabled boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT calendar_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT calendar_notifications_doctor_firebase_uid_fkey FOREIGN KEY (doctor_firebase_uid) REFERENCES public.doctors(firebase_uid)
);
CREATE TABLE public.doctors (
  id integer NOT NULL DEFAULT nextval('doctors_id_seq'::regclass),
  firebase_uid character varying NOT NULL UNIQUE,
  email character varying NOT NULL UNIQUE,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  specialization character varying,
  license_number character varying UNIQUE,
  phone character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  pathology_lab_phone character varying,
  pathology_lab_name character varying,
  radiology_lab_phone character varying,
  radiology_lab_name character varying,
  hospital_name character varying,
  CONSTRAINT doctors_pkey PRIMARY KEY (id)
);
CREATE TABLE public.frontdesk_users (
  id integer NOT NULL DEFAULT nextval('frontdesk_users_id_seq'::regclass),
  name character varying NOT NULL,
  phone character varying NOT NULL,
  hospital_name character varying NOT NULL,
  username character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT frontdesk_users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.handwritten_visit_notes (
  id bigint NOT NULL DEFAULT nextval('handwritten_visit_notes_id_seq'::regclass),
  visit_id bigint NOT NULL,
  patient_id bigint NOT NULL,
  doctor_firebase_uid text NOT NULL,
  template_id bigint,
  original_template_url text NOT NULL,
  handwritten_pdf_url text NOT NULL,
  handwritten_pdf_filename text NOT NULL,
  handwritten_pdf_size bigint,
  storage_path text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  sent_via_whatsapp boolean DEFAULT false,
  whatsapp_message_id text,
  is_active boolean DEFAULT true,
  CONSTRAINT handwritten_visit_notes_pkey PRIMARY KEY (id),
  CONSTRAINT handwritten_visit_notes_visit_id_fkey FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT handwritten_visit_notes_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT handwritten_visit_notes_doctor_firebase_uid_fkey FOREIGN KEY (doctor_firebase_uid) REFERENCES public.doctors(firebase_uid),
  CONSTRAINT handwritten_visit_notes_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.pdf_templates(id)
);
CREATE TABLE public.lab_contacts (
  id integer NOT NULL DEFAULT nextval('lab_contacts_id_seq'::regclass),
  doctor_firebase_uid text NOT NULL,
  lab_type character varying NOT NULL CHECK (lab_type::text = ANY (ARRAY['pathology'::character varying, 'radiology'::character varying]::text[])),
  lab_name character varying NOT NULL,
  contact_phone character varying NOT NULL,
  contact_email character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lab_contacts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.lab_report_requests (
  id integer NOT NULL DEFAULT nextval('lab_report_requests_id_seq'::regclass),
  visit_id integer NOT NULL,
  patient_id integer NOT NULL,
  doctor_firebase_uid text NOT NULL,
  lab_contact_id integer,
  patient_name character varying NOT NULL,
  report_type character varying NOT NULL CHECK (report_type::text = ANY (ARRAY['pathology'::character varying, 'radiology'::character varying]::text[])),
  test_name character varying NOT NULL,
  instructions text,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'uploaded'::character varying, 'completed'::character varying, 'expired'::character varying]::text[])),
  request_token text NOT NULL UNIQUE,
  report_id integer,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lab_report_requests_pkey PRIMARY KEY (id),
  CONSTRAINT lab_report_requests_visit_id_fkey FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT lab_report_requests_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT lab_report_requests_lab_contact_id_fkey FOREIGN KEY (lab_contact_id) REFERENCES public.lab_contacts(id),
  CONSTRAINT lab_report_requests_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.reports(id)
);
CREATE TABLE public.notifications (
  id integer NOT NULL DEFAULT nextval('notifications_id_seq'::regclass),
  doctor_firebase_uid text NOT NULL,
  title character varying NOT NULL,
  message text NOT NULL,
  notification_type character varying DEFAULT 'report_upload'::character varying,
  priority integer DEFAULT 1,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  read_at timestamp with time zone,
  metadata jsonb,
  CONSTRAINT notifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.patient_history_analysis (
  id integer NOT NULL DEFAULT nextval('patient_history_analysis_id_seq'::regclass),
  patient_id integer NOT NULL,
  doctor_firebase_uid text NOT NULL,
  analysis_period_start date,
  analysis_period_end date,
  total_visits integer DEFAULT 0,
  total_reports integer DEFAULT 0,
  model_used text NOT NULL DEFAULT 'gemini-2.0-flash-exp'::text,
  confidence_score numeric DEFAULT 0.0,
  raw_analysis text NOT NULL,
  comprehensive_summary text,
  medical_trajectory text,
  chronic_conditions ARRAY,
  recurring_patterns ARRAY,
  treatment_effectiveness text,
  risk_factors ARRAY,
  recommendations ARRAY,
  significant_findings ARRAY,
  lifestyle_factors text,
  medication_history text,
  follow_up_suggestions ARRAY,
  analysis_success boolean DEFAULT true,
  analysis_error text,
  processing_time_ms integer,
  analyzed_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT patient_history_analysis_pkey PRIMARY KEY (id),
  CONSTRAINT fk_patient_history_analysis_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT fk_patient_history_analysis_doctor FOREIGN KEY (doctor_firebase_uid) REFERENCES public.doctors(firebase_uid)
);
CREATE TABLE public.patients (
  id bigint NOT NULL DEFAULT nextval('patients_id_seq'::regclass),
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text,
  phone text NOT NULL,
  date_of_birth date NOT NULL,
  gender text NOT NULL CHECK (gender = ANY (ARRAY['Male'::text, 'Female'::text, 'Other'::text])),
  address text,
  emergency_contact_name text,
  emergency_contact_phone text,
  blood_group text,
  allergies text,
  medical_history text,
  created_by_doctor text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT patients_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pdf_templates (
  id bigint NOT NULL DEFAULT nextval('pdf_templates_id_seq'::regclass),
  doctor_firebase_uid text NOT NULL,
  template_name text NOT NULL,
  file_name text NOT NULL,
  file_url text NOT NULL,
  file_size bigint,
  storage_path text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pdf_templates_pkey PRIMARY KEY (id),
  CONSTRAINT pdf_templates_doctor_firebase_uid_fkey FOREIGN KEY (doctor_firebase_uid) REFERENCES public.doctors(firebase_uid)
);
CREATE TABLE public.pharmacy_inventory (
  id bigint NOT NULL DEFAULT nextval('pharmacy_inventory_id_seq'::regclass),
  pharmacy_id bigint NOT NULL,
  medicine_name text NOT NULL,
  sku text,
  batch_number text,
  expiry_date date,
  stock_quantity integer NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
  reorder_level integer DEFAULT 0 CHECK (reorder_level >= 0),
  unit text,
  purchase_price numeric,
  selling_price numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  supplier_id bigint,
  tax_percent numeric,
  CONSTRAINT pharmacy_inventory_pkey PRIMARY KEY (id),
  CONSTRAINT pharmacy_inventory_pharmacy_id_fkey FOREIGN KEY (pharmacy_id) REFERENCES public.pharmacy_users(id),
  CONSTRAINT pharmacy_inventory_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.pharmacy_suppliers(id)
);
CREATE TABLE public.pharmacy_invoices (
  id bigint NOT NULL DEFAULT nextval('pharmacy_invoices_id_seq'::regclass),
  pharmacy_id bigint NOT NULL,
  prescription_id bigint,
  invoice_number text NOT NULL UNIQUE,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  subtotal numeric NOT NULL DEFAULT 0,
  tax numeric NOT NULL DEFAULT 0,
  discount numeric NOT NULL DEFAULT 0,
  total_amount numeric NOT NULL DEFAULT 0,
  payment_method text,
  status text NOT NULL DEFAULT 'paid'::text CHECK (status = ANY (ARRAY['paid'::text, 'unpaid'::text, 'partially_paid'::text])),
  generated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pharmacy_invoices_pkey PRIMARY KEY (id),
  CONSTRAINT pharmacy_invoices_pharmacy_id_fkey FOREIGN KEY (pharmacy_id) REFERENCES public.pharmacy_users(id),
  CONSTRAINT pharmacy_invoices_prescription_id_fkey FOREIGN KEY (prescription_id) REFERENCES public.pharmacy_prescriptions(id)
);
CREATE TABLE public.pharmacy_prescriptions (
  id bigint NOT NULL DEFAULT nextval('pharmacy_prescriptions_id_seq'::regclass),
  pharmacy_id bigint,
  visit_id bigint NOT NULL,
  patient_id bigint NOT NULL,
  doctor_firebase_uid text NOT NULL,
  doctor_name text,
  doctor_specialization text,
  hospital_name text NOT NULL,
  patient_name text NOT NULL,
  patient_phone text,
  medications_text text,
  medications_json jsonb DEFAULT '[]'::jsonb,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'preparing'::text, 'ready'::text, 'dispensed'::text, 'cancelled'::text])),
  visit_date date,
  visit_type text,
  notes text,
  total_estimated_amount numeric,
  dispensed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pharmacy_prescriptions_pkey PRIMARY KEY (id),
  CONSTRAINT pharmacy_prescriptions_pharmacy_id_fkey FOREIGN KEY (pharmacy_id) REFERENCES public.pharmacy_users(id),
  CONSTRAINT pharmacy_prescriptions_visit_id_fkey FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT pharmacy_prescriptions_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT pharmacy_prescriptions_doctor_firebase_uid_fkey FOREIGN KEY (doctor_firebase_uid) REFERENCES public.doctors(firebase_uid),
  CONSTRAINT pharmacy_prescriptions_doctor_uid_fkey FOREIGN KEY (doctor_firebase_uid) REFERENCES public.doctors(firebase_uid)
);
CREATE TABLE public.pharmacy_suppliers (
  id bigint NOT NULL DEFAULT nextval('pharmacy_suppliers_id_seq'::regclass),
  pharmacy_id bigint NOT NULL,
  name text NOT NULL,
  contact_person text,
  phone text,
  email text,
  address text,
  notes text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT pharmacy_suppliers_pkey PRIMARY KEY (id),
  CONSTRAINT pharmacy_suppliers_pharmacy_id_fkey FOREIGN KEY (pharmacy_id) REFERENCES public.pharmacy_users(id)
);
CREATE TABLE public.pharmacy_users (
  id bigint NOT NULL DEFAULT nextval('pharmacy_users_id_seq'::regclass),
  name text NOT NULL,
  phone text,
  hospital_name text NOT NULL,
  username text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  is_active boolean DEFAULT true,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pharmacy_users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.report_upload_links (
  id integer NOT NULL DEFAULT nextval('report_upload_links_id_seq'::regclass),
  visit_id integer NOT NULL,
  patient_id integer NOT NULL,
  doctor_firebase_uid text NOT NULL,
  upload_token text NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT report_upload_links_pkey PRIMARY KEY (id),
  CONSTRAINT fk_upload_links_visit FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT fk_upload_links_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT fk_upload_links_doctor FOREIGN KEY (doctor_firebase_uid) REFERENCES public.doctors(firebase_uid)
);
CREATE TABLE public.reports (
  id integer NOT NULL DEFAULT nextval('reports_id_seq'::regclass),
  visit_id integer NOT NULL,
  patient_id integer NOT NULL,
  doctor_firebase_uid text NOT NULL,
  file_name text NOT NULL,
  file_size integer NOT NULL,
  file_type text NOT NULL,
  file_url text NOT NULL,
  notes text,
  upload_token text NOT NULL,
  uploaded_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  storage_path text,
  test_type text,
  CONSTRAINT reports_pkey PRIMARY KEY (id),
  CONSTRAINT fk_reports_visit FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT fk_reports_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT fk_reports_doctor FOREIGN KEY (doctor_firebase_uid) REFERENCES public.doctors(firebase_uid),
  CONSTRAINT fk_reports_upload_link FOREIGN KEY (upload_token) REFERENCES public.report_upload_links(upload_token)
);
CREATE TABLE public.visit_reports (
  id bigint NOT NULL DEFAULT nextval('visit_reports_id_seq'::regclass),
  visit_id bigint NOT NULL,
  patient_id bigint NOT NULL,
  doctor_firebase_uid text NOT NULL,
  template_id bigint,
  file_name text NOT NULL,
  file_url text NOT NULL,
  file_size bigint,
  storage_path text,
  generated_at timestamp with time zone DEFAULT now(),
  sent_via_whatsapp boolean DEFAULT false,
  whatsapp_message_id text,
  CONSTRAINT visit_reports_pkey PRIMARY KEY (id),
  CONSTRAINT visit_reports_visit_id_fkey FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT visit_reports_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT visit_reports_doctor_firebase_uid_fkey FOREIGN KEY (doctor_firebase_uid) REFERENCES public.doctors(firebase_uid),
  CONSTRAINT visit_reports_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.pdf_templates(id)
);
CREATE TABLE public.visits (
  id bigint NOT NULL DEFAULT nextval('visits_id_seq'::regclass),
  patient_id bigint NOT NULL,
  doctor_firebase_uid text NOT NULL,
  visit_date date NOT NULL,
  visit_time time without time zone,
  visit_type text NOT NULL,
  chief_complaint text NOT NULL,
  symptoms text,
  vitals jsonb,
  clinical_examination text,
  diagnosis text,
  treatment_plan text,
  medications text,
  tests_recommended text,
  follow_up_date date,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  consultation_fee numeric,
  additional_charges numeric,
  total_amount numeric,
  discount numeric,
  payment_status character varying DEFAULT 'unpaid'::character varying CHECK (payment_status::text = ANY (ARRAY['unpaid'::character varying, 'paid'::character varying, 'partially_paid'::character varying]::text[])),
  payment_method character varying CHECK ((payment_method::text = ANY (ARRAY['cash'::character varying, 'card'::character varying, 'upi'::character varying, 'bank_transfer'::character varying, 'cheque'::character varying]::text[])) OR payment_method IS NULL),
  payment_date date,
  notes_billing text,
  note_input_type character varying DEFAULT 'typed'::character varying CHECK (note_input_type::text = ANY (ARRAY['typed'::character varying, 'handwritten'::character varying]::text[])),
  handwritten_pdf_url text,
  handwritten_pdf_filename text,
  handwritten_pdf_size bigint,
  handwritten_pdf_storage_path text,
  selected_template_id bigint,
  follow_up_time time without time zone,
  CONSTRAINT visits_pkey PRIMARY KEY (id),
  CONSTRAINT visits_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT visits_selected_template_id_fkey FOREIGN KEY (selected_template_id) REFERENCES public.pdf_templates(id)
);